baseURL = 'https://blog.rottenwheel.com/'
languageCode = 'en-us'
title = 'rottenblog'
theme = 'rottentheme'
disableKinds = ['taxonomy']
enableRobotsTXT = true

[[menu.main]]
url = "/index.xml"
name = "RSS"

[menu]
[[menu.main]]
url = "/"
name = "blog"

[[menu.main]]
url = "https://rottenwheel.com"
name = "about"
