baseURL = 'https://blog.rottenwheel.com/'
languageCode = 'en-us'
title = 'rottenwheel'
theme = 'hugo-rottenwheel'
disableKinds = ['taxonomy']
enableRobotsTXT = true

[menu]
[[menu.main]]
url = "/"
name = "blog"

[[menu.main]]
url = "https://rottenwheel.com"
name = "about"
